"""inicio

Revision ID: 638d62f3b8fa
Revises: 
Create Date: 2026-04-23 19:32:49.522456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '638d62f3b8fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_estado'))
        batch_op.drop_index(batch_op.f('idx_fecha'))
        batch_op.drop_index(batch_op.f('idx_número_orden'))
        batch_op.drop_index(batch_op.f('idx_usuario'))
        batch_op.drop_index(batch_op.f('número_orden'))

    op.drop_table('ordenes')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_activo'))
        batch_op.drop_index(batch_op.f('idx_categoria'))
        batch_op.drop_index(batch_op.f('idx_género'))
        batch_op.drop_index(batch_op.f('idx_nombre'))
        batch_op.drop_index(batch_op.f('idx_precio'))
        batch_op.drop_index(batch_op.f('idx_productos_género_categoría'))
        batch_op.drop_index(batch_op.f('idx_slug'))
        batch_op.drop_index(batch_op.f('sku'))
        batch_op.drop_index(batch_op.f('slug'))

    op.drop_table('productos')
    with op.batch_alter_table('detalles_ordenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_orden'))

    op.drop_table('detalles_ordenes')
    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_carrito_usuario_fecha'))
        batch_op.drop_index(batch_op.f('idx_token'))
        batch_op.drop_index(batch_op.f('idx_usuario'))

    op.drop_table('carrito')
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_usuario'))
        batch_op.drop_index(batch_op.f('uq_usuario_producto'))

    op.drop_table('wishlist')
    with op.batch_alter_table('historial_promociones_usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_fecha'))
        batch_op.drop_index(batch_op.f('idx_historial_promociones'))
        batch_op.drop_index(batch_op.f('idx_usuario'))

    op.drop_table('historial_promociones_usuario')
    op.drop_table('cupones_temporada')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('idx_activo'))
        batch_op.drop_index(batch_op.f('idx_email'))
        batch_op.drop_index(batch_op.f('idx_rol'))

    op.drop_table('admins')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('idx_activo'))
        batch_op.drop_index(batch_op.f('idx_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('resenas_productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_producto'))
        batch_op.drop_index(batch_op.f('idx_usuario'))
        batch_op.drop_index(batch_op.f('uq_usuario_producto'))

    op.drop_table('resenas_productos')
    with op.batch_alter_table('envios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_número_seguimiento'))
        batch_op.drop_index(batch_op.f('idx_orden'))
        batch_op.drop_index(batch_op.f('número_seguimiento'))

    op.drop_table('envios')
    with op.batch_alter_table('metodos_pago', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_usuario'))

    op.drop_table('metodos_pago')
    with op.batch_alter_table('variantes_producto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_color_talla'))
        batch_op.drop_index(batch_op.f('idx_producto'))
        batch_op.drop_index(batch_op.f('sku_variante'))
        batch_op.drop_index(batch_op.f('uq_variante'))

    op.drop_table('variantes_producto')
    with op.batch_alter_table('direcciones_usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_por_defecto'))
        batch_op.drop_index(batch_op.f('idx_usuario'))

    op.drop_table('direcciones_usuario')
    with op.batch_alter_table('promociones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_activa'))
        batch_op.drop_index(batch_op.f('idx_destacada'))
        batch_op.drop_index(batch_op.f('idx_fechas'))
        batch_op.drop_index(batch_op.f('idx_promociones_género_categoria'))
        batch_op.drop_index(batch_op.f('idx_slug'))
        batch_op.drop_index(batch_op.f('slug'))

    op.drop_table('promociones')
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_género'))
        batch_op.drop_index(batch_op.f('idx_orden'))
        batch_op.drop_index(batch_op.f('idx_slug'))
        batch_op.drop_index(batch_op.f('nombre'))
        batch_op.drop_index(batch_op.f('slug'))

    op.drop_table('categorias')
    with op.batch_alter_table('productos_en_promoción', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_promoción'))
        batch_op.drop_index(batch_op.f('uq_producto_promoción'))

    op.drop_table('productos_en_promoción')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos_en_promoción',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('producto_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('promoción_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('descuento_aplicado', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('precio_promocional', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('fecha_creación', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('productos_en_promoción_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promoción_id'], ['promociones.id'], name=op.f('productos_en_promoción_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('productos_en_promoción', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_producto_promoción'), ['producto_id', 'promoción_id'], unique=True)
        batch_op.create_index(batch_op.f('idx_promoción'), ['promoción_id'], unique=False)

    op.create_table('categorias',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('descripción', mysql.TEXT(), nullable=True),
    sa.Column('imagen', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('slug', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('género', mysql.ENUM('dama', 'varón', 'infantil', 'unisex'), server_default=sa.text("'dama'"), nullable=True),
    sa.Column('orden', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('fecha_creación', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('activa', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('nombre'), ['nombre'], unique=True)
        batch_op.create_index(batch_op.f('idx_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('idx_orden'), ['orden'], unique=False)
        batch_op.create_index(batch_op.f('idx_género'), ['género'], unique=False)

    op.create_table('promociones',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('descripción', mysql.TEXT(), nullable=True),
    sa.Column('tipo', mysql.ENUM('porcentaje', 'cantidad_fija', 'envio_gratis', 'compra_x_lleva_y'), server_default=sa.text("'porcentaje'"), nullable=True),
    sa.Column('valor', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('valor_mínimo_compra', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('fecha_inicio', sa.DATE(), nullable=False),
    sa.Column('fecha_fin', sa.DATE(), nullable=False),
    sa.Column('aplica_a', mysql.ENUM('todos', 'dama', 'varón', 'infantil', 'categoria_específica'), server_default=sa.text("'todos'"), nullable=True),
    sa.Column('categoría_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('uso_máximo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('uso_actual', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('máximo_por_usuario', mysql.INTEGER(display_width=11), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('activa', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('destacada', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('mostrar_en_productos', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('imagen_banner', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('color_tema', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('fecha_creación', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('fecha_actualización', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['categoría_id'], ['categorias.id'], name=op.f('promociones_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('promociones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('idx_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('idx_promociones_género_categoria'), ['aplica_a', 'categoría_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_fechas'), ['fecha_inicio', 'fecha_fin'], unique=False)
        batch_op.create_index(batch_op.f('idx_destacada'), ['destacada'], unique=False)
        batch_op.create_index(batch_op.f('idx_activa'), ['activa'], unique=False)

    op.create_table('direcciones_usuario',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tipo', mysql.ENUM('envio', 'facturacion'), server_default=sa.text("'envio'"), nullable=True),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('nombre_completo', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('dirección', mysql.TEXT(), nullable=False),
    sa.Column('número_exterior', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('número_interior', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('apartado', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ciudad', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('provincia', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('código_postal', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('país', mysql.VARCHAR(length=50), server_default=sa.text("'PE'"), nullable=False),
    sa.Column('teléfono', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('instrucciones_entrega', mysql.TEXT(), nullable=True),
    sa.Column('por_defecto', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('fecha_creación', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('direcciones_usuario_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('direcciones_usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_usuario'), ['usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_por_defecto'), ['por_defecto'], unique=False)

    op.create_table('variantes_producto',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('producto_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('color', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('talla', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('stock', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('precio_adicional', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('sku_variante', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('imagen', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fecha_creación', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('variantes_producto_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('variantes_producto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_variante'), ['producto_id', 'color', 'talla'], unique=True)
        batch_op.create_index(batch_op.f('sku_variante'), ['sku_variante'], unique=True)
        batch_op.create_index(batch_op.f('idx_producto'), ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_color_talla'), ['color', 'talla'], unique=False)

    op.create_table('metodos_pago',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tipo', mysql.ENUM('tarjeta_credito', 'paypal', 'transferencia', 'efectivo'), server_default=sa.text("'tarjeta_credito'"), nullable=True),
    sa.Column('ultimos_digitos', mysql.VARCHAR(length=4), nullable=True),
    sa.Column('titular', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('fecha_vencimiento', mysql.VARCHAR(length=7), nullable=True),
    sa.Column('email_paypal', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('por_defecto', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('fecha_creación', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('metodos_pago_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('metodos_pago', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_usuario'), ['usuario_id'], unique=False)

    op.create_table('envios',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('orden_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('empresa_envío', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('número_seguimiento', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('estado', mysql.ENUM('preparando', 'recogida', 'en_tránsito', 'entregado', 'devuelto', 'cancelado'), server_default=sa.text("'preparando'"), nullable=True),
    sa.Column('ubicación_actual', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('fecha_envío', mysql.TIMESTAMP(), nullable=True),
    sa.Column('fecha_entrega_estimada', sa.DATE(), nullable=True),
    sa.Column('fecha_entrega_real', mysql.TIMESTAMP(), nullable=True),
    sa.Column('costo', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('peso', mysql.DECIMAL(precision=8, scale=3), nullable=True),
    sa.Column('fecha_creación', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('fecha_actualización', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], name=op.f('envios_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('envios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('número_seguimiento'), ['número_seguimiento'], unique=True)
        batch_op.create_index(batch_op.f('idx_orden'), ['orden_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_número_seguimiento'), ['número_seguimiento'], unique=False)

    op.create_table('resenas_productos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('producto_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('orden_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('calificación', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('título', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('contenido', mysql.TEXT(), nullable=True),
    sa.Column('verificado', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('útiles', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('fecha_creación', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('fecha_actualización', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], name=op.f('resenas_productos_ibfk_3'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('resenas_productos_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('resenas_productos_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('resenas_productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_usuario_producto'), ['usuario_id', 'producto_id'], unique=True)
        batch_op.create_index(batch_op.f('idx_usuario'), ['usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_producto'), ['producto_id'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('contraseña', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('teléfono', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('fecha_registro', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('último_login', mysql.TIMESTAMP(), nullable=True),
    sa.Column('activo', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('token_recuperacion', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('admins',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('contrasena', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('rol', mysql.ENUM('superadmin', 'editor', 'visor'), server_default=sa.text("'editor'"), nullable=True),
    sa.Column('activo', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('ultimo_login', mysql.TIMESTAMP(), nullable=True),
    sa.Column('fecha_creacion', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_rol'), ['rol'], unique=False)
        batch_op.create_index(batch_op.f('idx_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('cupones_temporada',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('código', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('promoción_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('descripción', mysql.TEXT(), nullable=True),
    sa.Column('tipo', mysql.ENUM('automático', 'manual'), server_default=sa.text("'automático'"), nullable=True),
    sa.Column('descuento', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('tipo_descuento', mysql.ENUM('porcentaje', 'cantidad_fija'), server_default=sa.text("'porcentaje'"), nullable=True),
    sa.Column('activo', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('uso_máximo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('uso_actual', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('fecha_creación', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['promoción_id'], ['promociones.id'], name=op.f('cupones_temporada_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('historial_promociones_usuario',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('promoción_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cupón_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('orden_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('descuento_aplicado', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('fecha_uso', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['cupón_id'], ['cupones_temporada.id'], name=op.f('historial_promociones_usuario_ibfk_3'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], name=op.f('historial_promociones_usuario_ibfk_4'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['promoción_id'], ['promociones.id'], name=op.f('historial_promociones_usuario_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('historial_promociones_usuario_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('historial_promociones_usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_usuario'), ['usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_historial_promociones'), ['usuario_id', 'fecha_uso'], unique=False)
        batch_op.create_index(batch_op.f('idx_fecha'), ['fecha_uso'], unique=False)

    op.create_table('wishlist',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('producto_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fecha_añadido', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('wishlist_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('wishlist_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_usuario_producto'), ['usuario_id', 'producto_id'], unique=True)
        batch_op.create_index(batch_op.f('idx_usuario'), ['usuario_id'], unique=False)

    op.create_table('carrito',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('token_sesion', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('producto_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('variante_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cantidad', mysql.INTEGER(display_width=11), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('precio_unitario', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('fecha_añadido', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('carrito_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('carrito_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variante_id'], ['variantes_producto.id'], name=op.f('carrito_ibfk_3'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_usuario'), ['usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_token'), ['token_sesion'], unique=False)
        batch_op.create_index(batch_op.f('idx_carrito_usuario_fecha'), ['usuario_id', 'fecha_añadido'], unique=False)

    op.create_table('detalles_ordenes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('orden_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('producto_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('variante_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('nombre_producto', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('cantidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('precio_unitario', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', mysql.DECIMAL(precision=10, scale=2), sa.Computed('(`cantidad` * `precio_unitario`)', persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], name=op.f('detalles_ordenes_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('detalles_ordenes_ibfk_2')),
    sa.ForeignKeyConstraint(['variante_id'], ['variantes_producto.id'], name=op.f('detalles_ordenes_ibfk_3'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('detalles_ordenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_orden'), ['orden_id'], unique=False)

    op.create_table('productos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('descripción', mysql.TEXT(), nullable=False),
    sa.Column('descripción_larga', mysql.LONGTEXT(), nullable=True),
    sa.Column('precio', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('precio_original', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('categoria_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('género', mysql.ENUM('dama', 'varón', 'infantil'), server_default=sa.text("'dama'"), nullable=False),
    sa.Column('subcategoría', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('stock', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('peso', mysql.DECIMAL(precision=8, scale=3), nullable=True),
    sa.Column('dimensiones', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('material', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sku', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('proveedor', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('imagen_principal', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('imagenes_adicionales', mysql.LONGTEXT(), nullable=True),
    sa.Column('es_destacado_temporada', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('fecha_creación', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('fecha_actualización', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('destacado', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], name=op.f('productos_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('sku'), ['sku'], unique=True)
        batch_op.create_index(batch_op.f('idx_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('idx_productos_género_categoría'), ['género', 'categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_precio'), ['precio'], unique=False)
        batch_op.create_index(batch_op.f('idx_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('idx_género'), ['género'], unique=False)
        batch_op.create_index(batch_op.f('idx_categoria'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_activo'), ['activo'], unique=False)

    op.create_table('ordenes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('número_orden', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('subtotal', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('costo_envío', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('descuento', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('descuento_promoción', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('total', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('estado', mysql.ENUM('pendiente', 'pagada', 'preparando', 'enviada', 'entregada', 'cancelada'), server_default=sa.text("'pendiente'"), nullable=True),
    sa.Column('dirección_envío', mysql.TEXT(), nullable=False),
    sa.Column('ciudad_envío', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('código_postal_envío', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('método_envío', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('empresa_envío', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('número_seguimiento', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('método_pago', mysql.ENUM('tarjeta_credito', 'paypal', 'transferencia', 'efectivo'), server_default=sa.text("'tarjeta_credito'"), nullable=True),
    sa.Column('notas_cliente', mysql.TEXT(), nullable=True),
    sa.Column('notas_admin', mysql.TEXT(), nullable=True),
    sa.Column('fecha_orden', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('fecha_pago', mysql.TIMESTAMP(), nullable=True),
    sa.Column('fecha_envío', mysql.TIMESTAMP(), nullable=True),
    sa.Column('fecha_entrega', mysql.TIMESTAMP(), nullable=True),
    sa.Column('fecha_actualización', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('ordenes_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('número_orden'), ['número_orden'], unique=True)
        batch_op.create_index(batch_op.f('idx_usuario'), ['usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_número_orden'), ['número_orden'], unique=False)
        batch_op.create_index(batch_op.f('idx_fecha'), ['fecha_orden'], unique=False)
        batch_op.create_index(batch_op.f('idx_estado'), ['estado'], unique=False)

    # ### end Alembic commands ###
